[package]
name = "pd-edge-abi"
version.workspace = true
edition.workspace = true
build = "build.rs"

[lib]
name = "edge_abi"

[features]
default = ["console", "http", "tls", "websocket"]
console = []
http = []
http2 = ["http"]
mqtt = []
tls = []
websocket = ["http"]
webrtc = ["http"]

[dependencies]
pd-host-function = { path = "../../rustscript/pd-host-function" }

[build-dependencies]
syn = { version = "2", features = ["full"] }
