//! Edge host registry composition.
//!
//! The edge runtime binds the published ABI (every name in
//! `edge_abi::FUNCTIONS`) and then installs the *implemented* functions of the
//! requested scopes. Both halves are descriptor-driven:
//!
//! - Unimplemented ABI functions keep the unbound placeholder adapter, which
//!   is the behavior the ABI promises for a scope that this build does not
//!   implement.
//! - Implemented functions come from the linkme inventory as descriptor
//!   factories generated by `#[pd_edge_host_function]`. The inventory is used
//!   *only* for edge module discovery (which scope declares the function); the
//!   contract itself — schema, binding class, adapter — comes from the
//!   descriptor, which is derived from the function's ABI declaration.
//!
//! Installation is transactional and deterministic: descriptors are ordered by
//! guest name before the single registry transaction, and a rejected
//! descriptor set leaves the registry untouched.

use std::collections::HashMap;
use std::sync::{OnceLock, RwLock};

use edge_abi::FUNCTIONS as EDGE_ABI_FUNCTIONS;
use vm::host_extension::{HostAdapterDescriptor, HostFunctionDescriptor};
use vm::{HostFunctionRegistry, Vm, VmError};

use super::descriptor::{install_edge_descriptors, unbound_edge_descriptor};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum EdgeHostScope {
    Runtime,
    Http,
    HttpExtension,
    Io,
    Transport,
    #[cfg(feature = "mqtt")]
    Mqtt,
    WebSocket,
    #[cfg(feature = "webrtc")]
    WebRtc,
    Proxy,
    #[cfg(feature = "console")]
    Console,
}

/// One discoverable edge host function: the scope it belongs to and the
/// descriptor factory that carries its whole contract.
pub(crate) struct EdgeHostRegistration {
    pub scope: EdgeHostScope,
    pub descriptor: fn() -> HostFunctionDescriptor,
}

#[::linkme::distributed_slice]
pub(crate) static PD_EDGE_HOST_FUNCTIONS: [EdgeHostRegistration];

pub(crate) const EDGE_HOST_SCOPE_MASK_RUNTIME: u16 = 1 << 0;
pub(crate) const EDGE_HOST_SCOPE_MASK_HTTP: u16 = 1 << 1;
pub(crate) const EDGE_HOST_SCOPE_MASK_HTTP_EXTENSION: u16 = 1 << 2;
pub(crate) const EDGE_HOST_SCOPE_MASK_IO: u16 = 1 << 3;
pub(crate) const EDGE_HOST_SCOPE_MASK_TRANSPORT: u16 = 1 << 4;
#[cfg(feature = "mqtt")]
pub(crate) const EDGE_HOST_SCOPE_MASK_MQTT: u16 = 1 << 5;
pub(crate) const EDGE_HOST_SCOPE_MASK_WEBSOCKET: u16 = 1 << 6;
#[cfg(feature = "webrtc")]
pub(crate) const EDGE_HOST_SCOPE_MASK_WEBRTC: u16 = 1 << 7;
pub(crate) const EDGE_HOST_SCOPE_MASK_PROXY: u16 = 1 << 8;
#[cfg(feature = "console")]
pub(crate) const EDGE_HOST_SCOPE_MASK_CONSOLE: u16 = 1 << 9;

fn scope_mask(scope: EdgeHostScope) -> u16 {
    match scope {
        EdgeHostScope::Runtime => EDGE_HOST_SCOPE_MASK_RUNTIME,
        EdgeHostScope::Http => EDGE_HOST_SCOPE_MASK_HTTP,
        EdgeHostScope::HttpExtension => EDGE_HOST_SCOPE_MASK_HTTP_EXTENSION,
        EdgeHostScope::Io => EDGE_HOST_SCOPE_MASK_IO,
        EdgeHostScope::Transport => EDGE_HOST_SCOPE_MASK_TRANSPORT,
        #[cfg(feature = "mqtt")]
        EdgeHostScope::Mqtt => EDGE_HOST_SCOPE_MASK_MQTT,
        EdgeHostScope::WebSocket => EDGE_HOST_SCOPE_MASK_WEBSOCKET,
        #[cfg(feature = "webrtc")]
        EdgeHostScope::WebRtc => EDGE_HOST_SCOPE_MASK_WEBRTC,
        EdgeHostScope::Proxy => EDGE_HOST_SCOPE_MASK_PROXY,
        #[cfg(feature = "console")]
        EdgeHostScope::Console => EDGE_HOST_SCOPE_MASK_CONSOLE,
    }
}

fn scopes_mask(scopes: &[EdgeHostScope]) -> u16 {
    let mut mask = 0u16;
    for scope in scopes {
        mask |= scope_mask(*scope);
    }
    mask
}

fn registration_matches_scope_mask(
    registration: &EdgeHostRegistration,
    scope_mask_bits: u16,
) -> bool {
    scope_mask_bits & scope_mask(registration.scope) != 0
}

/// Materializes the descriptors of every implemented function in the mask, in
/// deterministic guest-name order.
fn scope_descriptors(scope_mask_bits: u16) -> Vec<HostFunctionDescriptor> {
    let mut descriptors = PD_EDGE_HOST_FUNCTIONS
        .iter()
        .filter(|registration| registration_matches_scope_mask(registration, scope_mask_bits))
        .map(|registration| (registration.descriptor)())
        .collect::<Vec<_>>();
    descriptors.sort_by(|left, right| left.schema.name.cmp(&right.schema.name));
    descriptors
}

/// Implemented descriptors for the mask plus unbound placeholders for every
/// published ABI name the mask does not implement, plus reviewed extensions.
fn complete_scope_descriptors(scope_mask_bits: u16) -> Vec<HostFunctionDescriptor> {
    let implemented = scope_descriptors(scope_mask_bits);
    let mut by_name = HashMap::new();
    for descriptor in implemented {
        by_name.insert(descriptor.schema.name.clone(), descriptor);
    }
    let mut descriptors = Vec::new();
    for function in EDGE_ABI_FUNCTIONS {
        if let Some(descriptor) = by_name.remove(function.name) {
            descriptors.push(descriptor);
        } else {
            descriptors.push(unbound_edge_descriptor(function.name));
        }
    }
    let mut extras = by_name.into_values().collect::<Vec<_>>();
    extras.sort_by(|left, right| left.schema.name.cmp(&right.schema.name));
    descriptors.extend(extras);
    descriptors
}

fn registry_for_scope_mask(scope_mask_bits: u16) -> Result<HostFunctionRegistry, VmError> {
    let mut registry = HostFunctionRegistry::new();
    install_edge_descriptors(&mut registry, &complete_scope_descriptors(scope_mask_bits))?;
    Ok(registry)
}

fn cached_registry_for_scope_mask(scope_mask_bits: u16) -> Result<HostFunctionRegistry, VmError> {
    static REGISTRY_CACHE: OnceLock<RwLock<HashMap<u16, HostFunctionRegistry>>> = OnceLock::new();
    let cache = REGISTRY_CACHE.get_or_init(|| RwLock::new(HashMap::new()));
    if let Some(registry) = cache
        .read()
        .expect("edge host registry cache read lock should not be poisoned")
        .get(&scope_mask_bits)
        .cloned()
    {
        return Ok(registry);
    }

    let registry = registry_for_scope_mask(scope_mask_bits)?;

    let mut write_guard = cache
        .write()
        .expect("edge host registry cache write lock should not be poisoned");
    Ok(write_guard
        .entry(scope_mask_bits)
        .or_insert_with(|| registry)
        .clone())
}

fn apply_cached_builtin_overrides(vm: &mut Vm, scopes: &[EdgeHostScope]) -> Result<(), VmError> {
    if scopes
        .iter()
        .any(|scope| matches!(scope, EdgeHostScope::Io))
    {
        bind_host_scopes_direct(vm, &[EdgeHostScope::Io])?;
    }
    Ok(())
}

pub(crate) fn bind_host_scopes(vm: &mut Vm, scopes: &[EdgeHostScope]) -> Result<(), VmError> {
    let scope_mask_bits = scopes_mask(scopes);
    if scope_mask_bits == 0 {
        return Ok(());
    }
    cached_registry_for_scope_mask(scope_mask_bits)?.bind_vm_cached(vm)?;
    apply_cached_builtin_overrides(vm, scopes)?;
    Ok(())
}

/// Binds the mask's implemented functions directly onto a VM.
///
/// The descriptor supplies both the guest identity and the adapter, so this
/// path cannot bind an adapter under a name that its schema does not declare.
pub(crate) fn bind_host_scopes_direct(
    vm: &mut Vm,
    scopes: &[EdgeHostScope],
) -> Result<(), VmError> {
    for descriptor in scope_descriptors(scopes_mask(scopes)) {
        let name = descriptor.schema.name.clone();
        match &descriptor.adapter {
            HostAdapterDescriptor::StaticStack(function) => {
                vm.bind_static_stack_function(name, *function);
            }
            HostAdapterDescriptor::StaticArgs(function) => {
                vm.bind_static_args_function(name, *function);
            }
            adapter => {
                return Err(VmError::HostError(format!(
                    "edge host function '{name}' cannot be bound directly: {:?} adapter",
                    super::descriptor::adapter_binding_kind(adapter)
                )));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::super::descriptor::{EdgeGuestValueType, edge_function_descriptor};
    use super::*;
    use vm::host_extension::HostBindingDescriptor;
    use vm::{CallOutcome, HostBindingKind, Value, VmError, VmResult};

    fn args_adapter(_args: &[Value]) -> VmResult<CallOutcome> {
        Err(VmError::HostError(
            "test adapter is never called".to_string(),
        ))
    }

    fn stack_adapter(_vm: &mut Vm, _args: &[Value]) -> VmResult<CallOutcome> {
        Err(VmError::HostError(
            "test adapter is never called".to_string(),
        ))
    }

    #[test]
    fn every_discovered_registration_has_a_declared_contract() {
        use super::super::descriptor::{EDGE_EXTENSION_FUNCTIONS, edge_abi_function};
        assert!(
            !PD_EDGE_HOST_FUNCTIONS.is_empty(),
            "the edge discovery inventory must not be empty"
        );
        for registration in PD_EDGE_HOST_FUNCTIONS {
            let descriptor = (registration.descriptor)();
            let name = descriptor.schema.name.as_str();
            assert!(
                edge_abi_function(name).is_some() || EDGE_EXTENSION_FUNCTIONS.contains(&name),
                "edge host function '{name}' is declared by no published catalog and is not a \
                 reviewed edge extension"
            );
        }
    }

    #[test]
    fn the_edge_extension_surface_is_exactly_the_reviewed_list() {
        use super::super::descriptor::{EDGE_EXTENSION_FUNCTIONS, edge_abi_function};
        for registration in PD_EDGE_HOST_FUNCTIONS {
            let name = (registration.descriptor)().schema.name;
            if edge_abi_function(&name).is_none() {
                assert!(
                    EDGE_EXTENSION_FUNCTIONS.contains(&name.as_str()),
                    "unreviewed edge extension '{name}'"
                );
            }
        }
        for name in ["io::open", "io::exists", "http::request::body::eof"] {
            assert!(
                EDGE_EXTENSION_FUNCTIONS.contains(&name),
                "the reviewed extension surface must document '{name}'"
            );
        }
    }

    #[test]
    fn discovered_descriptors_are_sorted_and_unique_per_scope_mask() {
        let descriptors = scope_descriptors(u16::MAX);
        assert!(!descriptors.is_empty());
        for pair in descriptors.windows(2) {
            assert!(
                pair[0].schema.name < pair[1].schema.name,
                "descriptor order must be deterministic: {} vs {}",
                pair[0].schema.name,
                pair[1].schema.name
            );
        }
    }

    #[test]
    fn undeclared_descriptors_are_rejected_before_registration() {
        let mut registry = HostFunctionRegistry::empty();
        let descriptor = HostFunctionDescriptor {
            schema: vm::HostFunctionSchema::new("edge::not::declared", Vec::new()),
            binding: HostBindingDescriptor {
                kind: HostBindingKind::StaticArgs,
            },
            effects: Vec::new(),
            adapter: HostAdapterDescriptor::StaticArgs(args_adapter),
            resource_types: Vec::new(),
        };
        let error = install_edge_descriptors(&mut registry, &[descriptor])
            .expect_err("an undeclared descriptor must be rejected");
        assert!(error.to_string().contains("edge::not::declared"), "{error}");
        assert!(!registry.contains_name("edge::not::declared"));
    }

    #[test]
    fn a_rejected_descriptor_rolls_the_whole_installation_back() {
        let mut registry = HostFunctionRegistry::empty();
        let mut rejected = edge_function_descriptor(
            "runtime::sleep",
            &[("ms", EdgeGuestValueType::Int)],
            HostBindingKind::StaticStack,
            HostAdapterDescriptor::StaticStack(stack_adapter),
        );
        // A binding class that its adapter does not implement fails inside the
        // registry transaction, after an earlier descriptor was installed.
        rejected.binding = HostBindingDescriptor {
            kind: HostBindingKind::StaticStack,
        };
        rejected.adapter = HostAdapterDescriptor::StaticArgs(args_adapter);

        let accepted = edge_function_descriptor(
            "runtime::exit",
            &[],
            HostBindingKind::StaticStack,
            HostAdapterDescriptor::StaticStack(stack_adapter),
        );
        let error = install_edge_descriptors(&mut registry, &[rejected, accepted])
            .expect_err("the mismatched descriptor must fail the transaction");
        assert!(
            error.to_string().contains("binding/adapter mismatch")
                || error.to_string().contains("cannot be installed"),
            "{error}"
        );
        assert!(
            !registry.contains_name("runtime::exit"),
            "a failed installation must leave the registry untouched"
        );
    }

    #[test]
    fn installing_the_same_descriptor_twice_is_rejected() {
        let mut registry = HostFunctionRegistry::empty();
        let descriptor = edge_function_descriptor(
            "runtime::exit",
            &[],
            HostBindingKind::StaticStack,
            HostAdapterDescriptor::StaticStack(stack_adapter),
        );
        let duplicate = edge_function_descriptor(
            "runtime::exit",
            &[],
            HostBindingKind::StaticStack,
            HostAdapterDescriptor::StaticStack(stack_adapter),
        );
        let error = install_edge_descriptors(&mut registry, &[descriptor, duplicate])
            .expect_err("duplicate descriptors must be rejected");
        assert!(error.to_string().contains("duplicate"), "{error}");
    }

    #[test]
    fn invalid_scope_masks_bind_nothing() {
        assert!(scope_descriptors(0).is_empty());
        let mut registry = HostFunctionRegistry::empty();
        install_edge_descriptors(&mut registry, &[]).expect("an empty set is valid");
        assert!(!registry.contains_name("runtime::sleep"));
    }

    #[test]
    fn runtime_scope_registry_binds_every_declared_abi_function() {
        let registry = registry_for_scope_mask(EDGE_HOST_SCOPE_MASK_RUNTIME)
            .expect("the runtime scope registry must build");
        for function in EDGE_ABI_FUNCTIONS {
            assert!(
                registry.contains_name(function.name),
                "edge ABI function '{}' must stay bindable",
                function.name
            );
        }
    }

    #[test]
    fn every_reviewed_extension_is_implemented() {
        use super::super::descriptor::EDGE_EXTENSION_FUNCTIONS;
        assert_eq!(
            EDGE_EXTENSION_FUNCTIONS.len(),
            12,
            "the reviewed extension surface is exactly 12 names"
        );
        let implemented = PD_EDGE_HOST_FUNCTIONS
            .iter()
            .map(|registration| (registration.descriptor)().schema.name)
            .collect::<std::collections::BTreeSet<_>>();
        for name in EDGE_EXTENSION_FUNCTIONS {
            assert!(
                implemented.contains(*name),
                "reviewed extension '{name}' must be implemented in the discovery inventory"
            );
        }
    }

    #[test]
    fn restricted_registry_denies_before_install_and_authorizes_exact_imports() {
        let mut registry = HostFunctionRegistry::restricted();
        assert!(
            !registry.contains_name("tcp::stream::close"),
            "restricted registry must deny tcp::stream::close before install"
        );
        assert!(
            !registry.contains_name("udp::socket::close"),
            "restricted registry must deny udp::socket::close before install"
        );
        let installed = edge_function_descriptor(
            "tcp::stream::close",
            &[("stream", EdgeGuestValueType::Int)],
            HostBindingKind::StaticStack,
            HostAdapterDescriptor::StaticStack(stack_adapter),
        );
        install_edge_descriptors(&mut registry, &[installed])
            .expect("exact catalog install must succeed");
        assert!(
            registry.contains_name("tcp::stream::close"),
            "installed import must be authorized and bound"
        );
        assert!(
            !registry.contains_name("udp::socket::close"),
            "unlisted imports must remain denied"
        );
    }

    #[test]
    fn restricted_registry_rollback_leaves_no_partial_entries() {
        let mut registry = HostFunctionRegistry::restricted();
        let mut rejected = edge_function_descriptor(
            "tcp::stream::close",
            &[("stream", EdgeGuestValueType::Int)],
            HostBindingKind::StaticStack,
            HostAdapterDescriptor::StaticStack(stack_adapter),
        );
        rejected.adapter = HostAdapterDescriptor::StaticArgs(args_adapter);
        let accepted = edge_function_descriptor(
            "udp::socket::close",
            &[("socket", EdgeGuestValueType::Int)],
            HostBindingKind::StaticStack,
            HostAdapterDescriptor::StaticStack(stack_adapter),
        );
        let error = install_edge_descriptors(&mut registry, &[rejected, accepted])
            .expect_err("mismatched adapter must fail the transaction");
        assert!(
            error.to_string().contains("binding/adapter mismatch")
                || error.to_string().contains("cannot be installed"),
            "{error}"
        );
        assert!(
            !registry.contains_name("tcp::stream::close"),
            "rollback must leave no partial registry entries"
        );
        assert!(
            !registry.contains_name("udp::socket::close"),
            "rollback must not authorize later descriptors"
        );
    }
}
